#Deployment for frontend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: alexsuspis/finding-movies-to-watch_frontend
          ports:
            - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
---

#Deployment for backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: alexsuspis/finding-movies-to-watch_backend
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---

#Deployment for recommendation system
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-system
  labels:
    app: recommendation-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation-system
  template:
    metadata:
      labels:
        app: recommendation-system
    spec:
      containers:
        - name: recommendation-system
          image: alexsuspis/finding-movies-to-watch_recommendation-system
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-system
spec:
  selector:
    app: recommendation-system
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
