services:

  frontend:
    image: alexsuspis/finding-movies-to-watch_frontend
    container_name: frontend
    ports: 
      - "4200:4200"
    volumes:
      - /usr/src/app/frontend/node_modules

  backend:
    image: alexsuspis/finding-movies-to-watch_backend
    container_name: backend
    ports:
      - "8080:8080" 

  recommendation-system:
    image: alexsuspis/finding-movies-to-watch_recommendation-system
    container_name: recommendation_system
    ports:
      - "3000:3000"

